### ISSUE TITLE
Inconsistent Header Formatting and Link Matching in Table of Contents

### ISSUE THREAD

**Issue by Navneet1206** [Vyomx1010/C-Tutorial-By-Navneet#3]
Hey VyomX1010,

I found a couple of issues in the Markdown file:

1. **Inconsistent Index Links**: The links in the Index have some inconsistencies, particularly with extra spaces in titles (e.g., `1- Setting Up an IDE with MinGW` vs. `1. Setting Up an IDE with MinGW`), and the section numbering in the links doesn't always match the actual section numbering.
2. **Missing Subsection Links**: Some subsections, such as "Write and Run Your First Program" under both Code::Blocks and VS Code, don't have links for direct navigation.
3. **Repetitive Headings**: The term "Objective" is repeated frequently, which could be condensed or renamed to improve clarity.
4. **Header Level Inconsistencies**: There are some instances where headers are inconsistently used (e.g., `### Objective` under different sections).

It would be great if these could be fixed for better navigation and readability.

Thanks!

**Comment by Vyomx1010** [comment]
# Response to Feedback

Hi Navneet1206,

Thank you for your thorough review and for pointing out these issues! I appreciate your attention to detail. Here’s how I plan to address each of your points:

1. **Inconsistent Index Links**: I will review the index links and correct any inconsistencies in the titles and section numbering to ensure they match throughout the document.

2. **Missing Subsection Links**: I’ll add the necessary links for the subsections, including "Write and Run Your First Program" under both Code::Blocks and VS Code, to enhance navigation.

3. **Repetitive Headings**: I agree that the frequent use of "Objective" can be confusing. I’ll look into condensing or renaming these headings for better clarity.

4. **Header Level Inconsistencies**: I will go through the document to ensure that header levels are used consistently across all sections.

I’ll make these changes and update the Markdown file shortly. Thanks again for your valuable feedback!

Best,  
VyomX1010
